import { InStockEnum } from '../components/ProductCard/ProductCard.props'
import type { Characteristic, Product } from '../lib/catalog'

export const categories = [
  'Беговые дорожки',
  'Эллиптические',
  'Велотренажеры',
  'Степперы',
  'Горнолыжные',
  'Гребные тренажеры',
]

export const filtersTypes = {
  producer: [
    'Gym80',
    'CardioPower',
    'Original Fitness',
    'Nautilus',
    'Sole Fitness',
    'True Fitness',
    'Smith Strength',
  ],
  functionality: ['Самые продвинутые', 'Компактные', 'С моб. приложением'],
  discount: ['Акция', 'Новинки', 'В наличии', 'Наш выбор'],
}

const specs = (
  producer: string,
  first: [string, string],
  second: [string, string],
  third: [string, string],
): Characteristic[] => [
  { title: `${first[0]}: `, description: first[1] },
  { title: `${second[0]}: `, description: second[1] },
  { title: `${third[0]}: `, description: third[1] },
  { title: 'Производитель: ', description: producer },
]

export const cardioEquipments: Product[] = [
  {
    id: 1,
    category: 'Беговые дорожки',
    producer: 'CardioPower',
    title: 'Беговая дорожка CardioPower T20',
    price: 89900,
    oldPrice: 104900,
    rating: 5,
    popularity: 98,
    addedAt: '2026-03-10',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: true,
    functionality: ['С моб. приложением'],
    badges: ['like', 'percentage'],
    characteristics: specs(
      'CardioPower',
      ['Тип дорожки', 'Домашняя'],
      ['Бег.полотно', '1200 х 450 мм'],
      ['Мощность двигателя', '2,0 л.с.'],
    ),
  },
  {
    id: 2,
    category: 'Беговые дорожки',
    producer: 'Sole Fitness',
    title: 'Беговая дорожка Sole Fitness F63',
    price: 149900,
    rating: 4,
    popularity: 76,
    addedAt: '2026-06-01',
    inStock: InStockEnum.littleLeft,
    isNew: true,
    isChoice: false,
    functionality: ['Самые продвинутые', 'С моб. приложением'],
    badges: ['new'],
    characteristics: specs(
      'Sole Fitness',
      ['Тип дорожки', 'Полупрофессиональная'],
      ['Бег.полотно', '1400 х 510 мм'],
      ['Мощность двигателя', '3,25 л.с.'],
    ),
  },
  {
    id: 3,
    category: 'Эллиптические',
    producer: 'Nautilus',
    title: 'Эллиптический тренажер Nautilus E618',
    price: 119900,
    oldPrice: 134900,
    rating: 4,
    popularity: 64,
    addedAt: '2025-11-20',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: false,
    functionality: ['С моб. приложением'],
    badges: ['percentage'],
    characteristics: specs(
      'Nautilus',
      ['Длина шага', '51 см'],
      ['Уровни нагрузки', '25'],
      ['Маховик', '9 кг'],
    ),
  },
  {
    id: 4,
    category: 'Эллиптические',
    producer: 'True Fitness',
    title: 'Эллиптический тренажер True Fitness XC900',
    price: 329000,
    rating: 5,
    popularity: 55,
    addedAt: '2026-07-15',
    inStock: InStockEnum.coming,
    isNew: true,
    isChoice: true,
    functionality: ['Самые продвинутые'],
    badges: ['new', 'like'],
    characteristics: specs(
      'True Fitness',
      ['Длина шага', '56 см'],
      ['Уровни нагрузки', '40'],
      ['Маховик', '18 кг'],
    ),
  },
  {
    id: 5,
    category: 'Велотренажеры',
    producer: 'CardioPower',
    title: 'Вертикальный велотренажер CardioPower B37',
    price: 34900,
    oldPrice: 39900,
    rating: 5,
    popularity: 91,
    addedAt: '2026-01-12',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: true,
    functionality: ['Компактные'],
    badges: ['like', 'percentage'],
    characteristics: specs(
      'CardioPower',
      ['Тип', 'Вертикальный'],
      ['Уровни нагрузки', '16'],
      ['Маховик', '6 кг'],
    ),
  },
  {
    id: 6,
    category: 'Велотренажеры',
    producer: 'Original Fitness',
    title: 'Велотренажер Original Fitness RX-9',
    price: 58900,
    rating: 3,
    popularity: 42,
    addedAt: '2025-09-03',
    inStock: InStockEnum.notInStock,
    isNew: false,
    isChoice: false,
    functionality: ['Компактные'],
    badges: [],
    characteristics: specs(
      'Original Fitness',
      ['Тип', 'Горизонтальный'],
      ['Уровни нагрузки', '24'],
      ['Маховик', '8 кг'],
    ),
  },
  {
    id: 7,
    category: 'Степперы',
    producer: 'Gym80',
    title: 'Степпер Gym80 Stepper Pro',
    price: 72500,
    rating: 4,
    popularity: 33,
    addedAt: '2026-04-22',
    inStock: InStockEnum.inStock,
    isNew: true,
    isChoice: false,
    functionality: ['Компактные'],
    badges: ['new'],
    characteristics: specs(
      'Gym80',
      ['Высота ступени', '20 см'],
      ['Уровни нагрузки', '20'],
      ['Макс. вес', '150 кг'],
    ),
  },
  {
    id: 8,
    category: 'Степперы',
    producer: 'Smith Strength',
    title: 'Степпер Smith Strength ST-200',
    price: 46900,
    oldPrice: 52900,
    rating: 3,
    popularity: 38,
    addedAt: '2025-12-05',
    inStock: InStockEnum.littleLeft,
    isNew: false,
    isChoice: false,
    functionality: ['Компактные'],
    badges: ['percentage'],
    characteristics: specs(
      'Smith Strength',
      ['Высота ступени', '18 см'],
      ['Уровни нагрузки', '12'],
      ['Макс. вес', '130 кг'],
    ),
  },
  {
    id: 9,
    category: 'Горнолыжные',
    producer: 'Sole Fitness',
    title: 'Горнолыжный тренажер Sole Fitness SL-1',
    price: 219000,
    rating: 4,
    popularity: 21,
    addedAt: '2026-02-18',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: false,
    functionality: ['Самые продвинутые'],
    badges: [],
    characteristics: specs(
      'Sole Fitness',
      ['Длина шага', '70 см'],
      ['Уровни нагрузки', '10'],
      ['Макс. вес', '160 кг'],
    ),
  },
  {
    id: 10,
    category: 'Горнолыжные',
    producer: 'Nautilus',
    title: 'Горнолыжный тренажер Nautilus Ski Trainer',
    price: 174900,
    oldPrice: 189900,
    rating: 5,
    popularity: 27,
    addedAt: '2026-05-30',
    inStock: InStockEnum.inStock,
    isNew: true,
    isChoice: true,
    functionality: ['Самые продвинутые', 'С моб. приложением'],
    badges: ['new', 'like', 'percentage'],
    characteristics: specs(
      'Nautilus',
      ['Длина шага', '65 см'],
      ['Уровни нагрузки', '16'],
      ['Макс. вес', '150 кг'],
    ),
  },
  {
    id: 11,
    category: 'Гребные тренажеры',
    producer: 'True Fitness',
    title: 'Гребной тренажер True Fitness R5',
    price: 96900,
    rating: 4,
    popularity: 47,
    addedAt: '2026-03-28',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: true,
    functionality: ['Компактные'],
    badges: ['like'],
    characteristics: specs(
      'True Fitness',
      ['Тип сопротивления', 'Воздушное'],
      ['Длина рейки', '210 см'],
      ['Макс. вес', '180 кг'],
    ),
  },
  {
    id: 12,
    category: 'Гребные тренажеры',
    producer: 'Gym80',
    title: 'Гребной тренажер Gym80 Row Elite',
    price: 189900,
    oldPrice: 209900,
    rating: 5,
    popularity: 29,
    addedAt: '2026-07-02',
    inStock: InStockEnum.littleLeft,
    isNew: true,
    isChoice: false,
    functionality: ['Самые продвинутые'],
    badges: ['new', 'percentage'],
    characteristics: specs(
      'Gym80',
      ['Тип сопротивления', 'Магнитное'],
      ['Длина рейки', '200 см'],
      ['Макс. вес', '200 кг'],
    ),
  },
]
