import { InStockEnum } from '../components/ProductCard/ProductCard.props'
import type { Characteristic, Product } from '../lib/catalog'

export const categories = [
  'Treadmills',
  'Elliptical trainers',
  'Exercise bikes',
  'Steppers',
  'Ski trainers',
  'Rowing machines',
]

export const filtersTypes = {
  producer: [
    'Gym80',
    'CardioPower',
    'Original Fitness',
    'Nautilus',
    'Sole Fitness',
    'True Fitness',
    'Smith Strength',
  ],
  functionality: ['Most advanced', 'Compact', 'With mobile app'],
  discount: ['Sale', 'New arrivals', 'In stock', 'Our pick'],
}

const specs = (
  producer: string,
  first: [string, string],
  second: [string, string],
  third: [string, string],
): Characteristic[] => [
  { title: `${first[0]}: `, description: first[1] },
  { title: `${second[0]}: `, description: second[1] },
  { title: `${third[0]}: `, description: third[1] },
  { title: 'Manufacturer: ', description: producer },
]

export const cardioEquipments: Product[] = [
  {
    id: 1,
    category: 'Treadmills',
    producer: 'CardioPower',
    title: 'Treadmill CardioPower T20',
    price: 1799,
    oldPrice: 2099,
    rating: 5,
    popularity: 98,
    addedAt: '2026-03-10',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: true,
    functionality: ['With mobile app'],
    badges: ['like', 'percentage'],
    characteristics: specs(
      'CardioPower',
      ['Treadmill type', 'Home'],
      ['Running belt', '1200 x 450 mm'],
      ['Motor power', '2.0 hp'],
    ),
  },
  {
    id: 2,
    category: 'Treadmills',
    producer: 'Sole Fitness',
    title: 'Treadmill Sole Fitness F63',
    price: 2999,
    rating: 4,
    popularity: 76,
    addedAt: '2026-06-01',
    inStock: InStockEnum.littleLeft,
    isNew: true,
    isChoice: false,
    functionality: ['Most advanced', 'With mobile app'],
    badges: ['new'],
    characteristics: specs(
      'Sole Fitness',
      ['Treadmill type', 'Semi-professional'],
      ['Running belt', '1400 x 510 mm'],
      ['Motor power', '3,25 hp'],
    ),
  },
  {
    id: 3,
    category: 'Elliptical trainers',
    producer: 'Nautilus',
    title: 'Elliptical trainer Nautilus E618',
    price: 2399,
    oldPrice: 2699,
    rating: 4,
    popularity: 64,
    addedAt: '2025-11-20',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: false,
    functionality: ['With mobile app'],
    badges: ['percentage'],
    characteristics: specs(
      'Nautilus',
      ['Stride length', '51 cm'],
      ['Resistance levels', '25'],
      ['Flywheel', '9 kg'],
    ),
  },
  {
    id: 4,
    category: 'Elliptical trainers',
    producer: 'True Fitness',
    title: 'Elliptical trainer True Fitness XC900',
    price: 6590,
    rating: 5,
    popularity: 55,
    addedAt: '2026-07-15',
    inStock: InStockEnum.coming,
    isNew: true,
    isChoice: true,
    functionality: ['Most advanced'],
    badges: ['new', 'like'],
    characteristics: specs(
      'True Fitness',
      ['Stride length', '56 cm'],
      ['Resistance levels', '40'],
      ['Flywheel', '18 kg'],
    ),
  },
  {
    id: 5,
    category: 'Exercise bikes',
    producer: 'CardioPower',
    title: 'Upright exercise bike CardioPower B37',
    price: 699,
    oldPrice: 799,
    rating: 5,
    popularity: 91,
    addedAt: '2026-01-12',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: true,
    functionality: ['Compact'],
    badges: ['like', 'percentage'],
    characteristics: specs(
      'CardioPower',
      ['Type', 'Upright'],
      ['Resistance levels', '16'],
      ['Flywheel', '6 kg'],
    ),
  },
  {
    id: 6,
    category: 'Exercise bikes',
    producer: 'Original Fitness',
    title: 'Exercise bike Original Fitness RX-9',
    price: 1179,
    rating: 3,
    popularity: 42,
    addedAt: '2025-09-03',
    inStock: InStockEnum.notInStock,
    isNew: false,
    isChoice: false,
    functionality: ['Compact'],
    badges: [],
    characteristics: specs(
      'Original Fitness',
      ['Type', 'Recumbent'],
      ['Resistance levels', '24'],
      ['Flywheel', '8 kg'],
    ),
  },
  {
    id: 7,
    category: 'Steppers',
    producer: 'Gym80',
    title: 'Stepper Gym80 Stepper Pro',
    price: 1449,
    rating: 4,
    popularity: 33,
    addedAt: '2026-04-22',
    inStock: InStockEnum.inStock,
    isNew: true,
    isChoice: false,
    functionality: ['Compact'],
    badges: ['new'],
    characteristics: specs(
      'Gym80',
      ['Step height', '20 cm'],
      ['Resistance levels', '20'],
      ['Max weight', '150 kg'],
    ),
  },
  {
    id: 8,
    category: 'Steppers',
    producer: 'Smith Strength',
    title: 'Stepper Smith Strength ST-200',
    price: 939,
    oldPrice: 1059,
    rating: 3,
    popularity: 38,
    addedAt: '2025-12-05',
    inStock: InStockEnum.littleLeft,
    isNew: false,
    isChoice: false,
    functionality: ['Compact'],
    badges: ['percentage'],
    characteristics: specs(
      'Smith Strength',
      ['Step height', '18 cm'],
      ['Resistance levels', '12'],
      ['Max weight', '130 kg'],
    ),
  },
  {
    id: 9,
    category: 'Ski trainers',
    producer: 'Sole Fitness',
    title: 'Ski trainer Sole Fitness SL-1',
    price: 4380,
    rating: 4,
    popularity: 21,
    addedAt: '2026-02-18',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: false,
    functionality: ['Most advanced'],
    badges: [],
    characteristics: specs(
      'Sole Fitness',
      ['Stride length', '70 cm'],
      ['Resistance levels', '10'],
      ['Max weight', '160 kg'],
    ),
  },
  {
    id: 10,
    category: 'Ski trainers',
    producer: 'Nautilus',
    title: 'Ski trainer Nautilus Ski Trainer',
    price: 3499,
    oldPrice: 3799,
    rating: 5,
    popularity: 27,
    addedAt: '2026-05-30',
    inStock: InStockEnum.inStock,
    isNew: true,
    isChoice: true,
    functionality: ['Most advanced', 'With mobile app'],
    badges: ['new', 'like', 'percentage'],
    characteristics: specs(
      'Nautilus',
      ['Stride length', '65 cm'],
      ['Resistance levels', '16'],
      ['Max weight', '150 kg'],
    ),
  },
  {
    id: 11,
    category: 'Rowing machines',
    producer: 'True Fitness',
    title: 'Rowing machine True Fitness R5',
    price: 1939,
    rating: 4,
    popularity: 47,
    addedAt: '2026-03-28',
    inStock: InStockEnum.inStock,
    isNew: false,
    isChoice: true,
    functionality: ['Compact'],
    badges: ['like'],
    characteristics: specs(
      'True Fitness',
      ['Resistance type', 'Air'],
      ['Rail length', '210 cm'],
      ['Max weight', '180 kg'],
    ),
  },
  {
    id: 12,
    category: 'Rowing machines',
    producer: 'Gym80',
    title: 'Rowing machine Gym80 Row Elite',
    price: 3799,
    oldPrice: 4199,
    rating: 5,
    popularity: 29,
    addedAt: '2026-07-02',
    inStock: InStockEnum.littleLeft,
    isNew: true,
    isChoice: false,
    functionality: ['Most advanced'],
    badges: ['new', 'percentage'],
    characteristics: specs(
      'Gym80',
      ['Resistance type', 'Magnetic'],
      ['Rail length', '200 cm'],
      ['Max weight', '200 kg'],
    ),
  },
]
