import { InStockEnum } from '../components/ProductCard/ProductCard.props'

export const discount = [
  {
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Treadmill CardioPower S35',
    rating: 5,
    price: '1 134 900',
    oldPrice: '1 154 900',
    button: true,
  },
  {
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.littleLeft,
    title: 'Treadmill CardioPower S35',
    rating: 5,
    price: '1 134 900',
    oldPrice: '1 154 900',
    button: true,
  },
  {
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.coming,
    title: 'Treadmill CardioPower S35',
    rating: 5,
    price: '1 134 900',
    oldPrice: '1 154 900',
    button: true,
  },
  {
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.littleLeft,
    title: 'Treadmill CardioPower S35',
    rating: 5,
    price: '1 134 900',
    oldPrice: '1 154 900',
    button: true,
  },
  {
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.coming,
    title: 'Treadmill CardioPower S35',
    rating: 5,
    price: '1 134 900',
    oldPrice: '1 154 900',
    button: true,
  },
  {
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.notInStock,
    title: 'Treadmill CardioPower S35',
    rating: 5,
    price: '1 134 900',
    oldPrice: '1 154 900',
    button: true,
  },
]
