export const forHomeCatalog = [
  {
    image: '/images/forHome/one.png',
    title: 'Cardio equipment',
    list: [
      { title: 'Treadmills', quantity: 57 },
      { title: 'Elliptical trainers', quantity: 27 },
      { title: 'Exercise bikes', quantity: 19 },
      { title: 'Steppers', quantity: 17 },
      { title: 'Rowing machines', quantity: 5 },
      { title: 'Indoor cycling', quantity: 20 },
      { title: 'Ski trainers', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/two.png',
    title: 'Cardio equipment',
    list: [
      { title: 'Treadmills', quantity: 57 },
      { title: 'Elliptical trainers', quantity: 27 },
      { title: 'Exercise bikes', quantity: 19 },
      { title: 'Steppers', quantity: 17 },
      { title: 'Rowing machines', quantity: 5 },
      { title: 'Indoor cycling', quantity: 20 },
      { title: 'Ski trainers', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/three.png',
    title: 'Cardio equipment',
    list: [
      { title: 'Treadmills', quantity: 57 },
      { title: 'Elliptical trainers', quantity: 27 },
      { title: 'Exercise bikes', quantity: 19 },
      { title: 'Steppers', quantity: 17 },
      { title: 'Rowing machines', quantity: 5 },
      { title: 'Indoor cycling', quantity: 20 },
      { title: 'Ski trainers', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/four.png',
    title: 'Cardio equipment',
    list: [
      { title: 'Treadmills', quantity: 57 },
      { title: 'Elliptical trainers', quantity: 27 },
      { title: 'Exercise bikes', quantity: 19 },
      { title: 'Steppers', quantity: 17 },
      { title: 'Rowing machines', quantity: 5 },
      { title: 'Indoor cycling', quantity: 20 },
      { title: 'Ski trainers', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/one.png',
    title: 'Cardio equipment',
    list: [
      { title: 'Treadmills', quantity: 57 },
      { title: 'Elliptical trainers', quantity: 27 },
      { title: 'Exercise bikes', quantity: 19 },
      { title: 'Steppers', quantity: 17 },
      { title: 'Rowing machines', quantity: 5 },
      { title: 'Indoor cycling', quantity: 20 },
      { title: 'Ski trainers', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/two.png',
    title: 'Cardio equipment',
    list: [
      { title: 'Treadmills', quantity: 57 },
      { title: 'Elliptical trainers', quantity: 27 },
      { title: 'Exercise bikes', quantity: 19 },
      { title: 'Steppers', quantity: 17 },
      { title: 'Rowing machines', quantity: 5 },
      { title: 'Indoor cycling', quantity: 20 },
      { title: 'Ski trainers', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/three.png',
    title: 'Cardio equipment',
    list: [
      { title: 'Treadmills', quantity: 57 },
      { title: 'Elliptical trainers', quantity: 27 },
      { title: 'Exercise bikes', quantity: 19 },
      { title: 'Steppers', quantity: 17 },
      { title: 'Rowing machines', quantity: 5 },
      { title: 'Indoor cycling', quantity: 20 },
      { title: 'Ski trainers', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/four.png',
    title: 'Cardio equipment',
    list: [
      { title: 'Treadmills', quantity: 57 },
      { title: 'Elliptical trainers', quantity: 27 },
      { title: 'Exercise bikes', quantity: 19 },
      { title: 'Steppers', quantity: 17 },
      { title: 'Rowing machines', quantity: 5 },
      { title: 'Indoor cycling', quantity: 20 },
      { title: 'Ski trainers', quantity: 14 },
    ],
  },
]
